runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /hostcss
  static_files: css/host.css
  upload: host\.css
- url: /css
  static_dir: css
- url: .*
  script: Final.app

libraries:
- name: jinja2
  version: latest
